[app]
build_directory = "./"
sdk = "C"
devices = ["nanos", "nanox", "nanos+", "stax", "flex"]

[use_cases] # Coherent build options that make sense for your application
use_test_keys = "CAL_TEST_KEY=1 TRUSTED_NAME_TEST_KEY=1"
dbg_use_test_keys = "DEBUG=1 CAL_TEST_KEY=1 TRUSTED_NAME_TEST_KEY=1"

[tests]
pytest_directory = "./tests/"